site_name: "Site de Documentation GPGEOM"

theme:
  name: material
  palette:
    - scheme: default
      primary: light green
      accent: pink
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy


nav:
  - Accueil: index.md

  - IGN: 1_ign.md 

  - Générale donnée et métadonnée:
      - Métadonnée: 2_metadonnees.md
      - Intérpérabilité: 3_interoperabilite.md 
      - Sources: 6_source.md 


  - Invite de commande sur ubuntu:
      - Administration: 7_administrer_son_serveur.md
      - rappel commande: 4_ogr_gdal.md
      - OGR/GDAL (suite): 5_ogr_gdal_2.md


extra_css:
  - stylesheets/extra.css